
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.22000 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 2024/3/25 17:33:51。
      
      节点 1 上的项目“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\3.27.7\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\3.27.7\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\3.27.7\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.79
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/3.27.7/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
      生成启动时间为 2024/3/25 17:33:52。
      
      节点 1 上的项目“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\3.27.7\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        正在对“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”执行 Touch 任务。
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\3.27.7\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\3.27.7\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.55
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/3.27.7/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-2etd6s"
      binary: "D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-2etd6s"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-2etd6s'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_86cc0.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 2024/3/25 17:33:53。
        
        节点 1 上的项目“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-2etd6s\\cmTC_86cc0.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_86cc0.dir\\Debug\\”。
          正在创建目录“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-2etd6s\\Debug\\”。
          正在创建目录“cmTC_86cc0.dir\\Debug\\cmTC_86cc0.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_86cc0.dir\\Debug\\cmTC_86cc0.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_86cc0.dir\\Debug\\cmTC_86cc0.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_86cc0.dir\\Debug\\\\" /Fd"cmTC_86cc0.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32822 版
          CMakeCCompilerABI.c
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_86cc0.dir\\Debug\\\\" /Fd"cmTC_86cc0.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-2etd6s\\Debug\\cmTC_86cc0.exe" /INCREMENTAL /ILK:"cmTC_86cc0.dir\\Debug\\cmTC_86cc0.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-2etd6s/Debug/cmTC_86cc0.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-2etd6s/Debug/cmTC_86cc0.lib" /MACHINE:X64  /machine:x64 cmTC_86cc0.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_86cc0.vcxproj -> D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-2etd6s\\Debug\\cmTC_86cc0.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_86cc0.dir\\Debug\\cmTC_86cc0.tlog\\unsuccessfulbuild”。
          正在对“cmTC_86cc0.dir\\Debug\\cmTC_86cc0.tlog\\cmTC_86cc0.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-2etd6s\\cmTC_86cc0.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.56
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-mj10bg"
      binary: "D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-mj10bg"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-mj10bg'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_ffedd.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        适用于 .NET Framework MSBuild 版本 17.7.2+d6990bcfa
        生成启动时间为 2024/3/25 17:33:54。
        
        节点 1 上的项目“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-mj10bg\\cmTC_ffedd.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_ffedd.dir\\Debug\\”。
          正在创建目录“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-mj10bg\\Debug\\”。
          正在创建目录“cmTC_ffedd.dir\\Debug\\cmTC_ffedd.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_ffedd.dir\\Debug\\cmTC_ffedd.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
          正在对“cmTC_ffedd.dir\\Debug\\cmTC_ffedd.tlog\\unsuccessfulbuild”执行 Touch 任务。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_ffedd.dir\\Debug\\\\" /Fd"cmTC_ffedd.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32822 版
          CMakeCXXCompilerABI.cpp
          版权所有(C) Microsoft Corporation。保留所有权利。
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_ffedd.dir\\Debug\\\\" /Fd"cmTC_ffedd.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-mj10bg\\Debug\\cmTC_ffedd.exe" /INCREMENTAL /ILK:"cmTC_ffedd.dir\\Debug\\cmTC_ffedd.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-mj10bg/Debug/cmTC_ffedd.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/PennCGGT/CIS6600/autoringTool/houdiniPlugin/CMakeFiles/CMakeScratch/TryCompile-mj10bg/Debug/cmTC_ffedd.lib" /MACHINE:X64  /machine:x64 cmTC_ffedd.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_ffedd.vcxproj -> D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-mj10bg\\Debug\\cmTC_ffedd.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_ffedd.dir\\Debug\\cmTC_ffedd.tlog\\unsuccessfulbuild”。
          正在对“cmTC_ffedd.dir\\Debug\\cmTC_ffedd.tlog\\cmTC_ffedd.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\PennCGGT\\CIS6600\\autoringTool\\houdiniPlugin\\CMakeFiles\\CMakeScratch\\TryCompile-mj10bg\\cmTC_ffedd.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.57
        
      exitCode: 0
...
